# Generated by Django 6.0.1 on 2026-02-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtype',
            name='category',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Recurring'), ('IMPROMPTU', 'Impromptu / Emergency'), ('PROJECT', 'Specific Project')], default='PROJECT', max_length=20),
        ),
    ]
