# Generated by Django 6.0.1 on 2026-02-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donationtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
