# Generated by Django 6.0.1 on 2026-02-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donationtype_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonationsettings',
            name='auto_charge_card',
            field=models.BooleanField(default=False, help_text='Auto-charge saved card if Money Box is insufficient'),
        ),
        migrations.AddField(
            model_name='userdonationsettings',
            name='auto_deduct_from_box',
            field=models.BooleanField(default=True, help_text='Auto-deduct from Money Box'),
        ),
    ]
