# Generated by Django 6.0 on 2026-02-25 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_welfarefamilyneeddonation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaqfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('waqf_category', models.CharField(choices=[('MASJID', 'Masjid and Centres'), ('KNOWLEDGE', 'Knowledge and Scholarships'), ('INCOME', 'Income Generating Projects')], max_length=20)),
                ('project_type', models.CharField(help_text='e.g. Land, Borehole, Books', max_length=100)),
                ('contribution_method', models.CharField(choices=[('EXECUTE', 'Execute in my name (Project Request)'), ('HANDOVER', 'Hand over / Surrender asset to Ishrakaat')], max_length=20)),
                ('preferred_date', models.DateField(help_text='Target date for project or handover')),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waqf_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
