# Generated by Django 6.0 on 2026-02-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_waqfinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='waqfinterest',
            name='on_behalf_of',
            field=models.CharField(blank=True, help_text='Name to be associated with the project', max_length=100),
        ),
    ]
