# Generated by Django 6.0 on 2026-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='waqfinterest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='waqfinterest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FOLLOWED_UP', 'Followed Up'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='welfarefamilyneeddonation',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='welfarefamilyneeddonation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISBURSED', 'Disbursed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
