# Generated by Django 6.0.1 on 2026-02-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZakahNisab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_price_usd', models.DecimalField(decimal_places=2, help_text='Price per Ounce in USD', max_digits=10)),
                ('silver_price_usd', models.DecimalField(decimal_places=2, help_text='Price per Ounce in USD', max_digits=10)),
                ('usd_ngn_rate', models.DecimalField(decimal_places=2, help_text='Exchange rate USD to NGN', max_digits=10)),
                ('nisab_gold_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nisab_silver_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
