# Generated by Django 6.0.2 on 2026-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakahReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source_url', models.URLField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
