# Generated by Django 6.0 on 2026-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0002_zakahreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardIslamicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('arabic_title', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField()),
                ('arabic_content', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
