# Generated by Django for creating NisabData model

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0003_dashboardislamiccard'),
    ]

    operations = [
        migrations.CreateModel(
            name='nisabdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='NGN', max_length=3, serialize=False, verbose_name='Currency')),
                ('gold_price_per_gram', models.DecimalField(decimal_places=2, max_digits=10, serialize=False, verbose_name='Gold price per gram')),
                ('silver_price_per_gram', models.DecimalField(decimal_places=2, max_digits=10, serialize=False, verbose_name='Silver price per gram')),
                ('source', models.CharField(default='Unknown', max_length=255, serialize=False, verbose_name='Source')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, serialize=False, verbose_name='Last updated')),
            ],
            options={
                'verbose_name': 'Nisab Data',
                'verbose_name_plural': 'Nisab Data',
                'db_table': 'zakah_nisabdata',
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
