# Generated by Django 6.0.2 on 2026-03-14 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah', '0005_nisabdata_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nisabdata',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterField(
            model_name='nisabdata',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='nisabdata',
            name='gold_price_per_gram',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nisabdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nisabdata',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nisabdata',
            name='silver_price_per_gram',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nisabdata',
            name='source',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterModelTable(
            name='nisabdata',
            table=None,
        ),
    ]
