# Generated by Django 6.0 on 2026-02-21 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_paystack_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_level',
            field=models.CharField(choices=[('NONE', 'Regular user'), ('WARD', 'Ward admin'), ('LOCAL_GOVT', 'Local government admin'), ('STATE', 'State admin'), ('NATIONAL', 'National admin')], default='NONE', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(choices=[('WARD', 'Ward'), ('LOCAL_GOVT', 'Local government'), ('STATE', 'State'), ('NATIONAL', 'National')], default='STATE', max_length=20)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('local_govt', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('CALL', 'Call')], default='TEXT', max_length=20)),
                ('content', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
