# Generated by Django 6.0 on 2026-02-21 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_admin_level_adminchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchatmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_admin_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminchatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('CALL', 'Call'), ('VIDEO', 'Video'), ('CONFERENCE', 'Conference')], default='TEXT', max_length=20),
        ),
    ]
